name: Generate Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate Heatmap
        run: |
          mkdir -p dist
          python scripts/generate_heatmap.py

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: CodeNinja22-AS
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
